language: elixir

elixir:
  - '1.6.4'
otp_release: '20.3'

# TODO: Add mix test to CI
script:
  - mix credo
  - mix format --check-formatted
  - mix test --no-start

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doc
  on:
    branch: travis-docs
